name: "Dynamic matrix test"
pr: none
trigger: none
resources:
  pipelines:
    - pipeline: samplejobs   # Name of the pipeline resource
      source: pg_auto_failover.sample-jobs # Name of the pipeline referenced by the pipeline resource
      trigger:
        branches:
          - releases/*
          - main
          - gindibay-azure-pipelines-test
jobs:
  - job: generator
    steps:
      - bash: echo "##vso[task.setVariable variable=legs;isOutput=true]{'a':{'myvar':'A'}, 'b':{'myvar':'B'}}"
        name: mtrx
    # This expands to the matrix
    #   a:
    #     myvar: A
    #   b:
    #     myvar: B
  - job: runner
    dependsOn: generator
    strategy:
      matrix: $[ dependencies.generator.outputs['mtrx.legs'] ]
    steps:
      - script: echo $(myvar) # echos A or B depending on which leg is running
