name: samplejobs
pr: none
trigger:
  - none
jobs:
  - job: A
    steps:
      - script: echo A successfull

  - job: B
    dependsOn: A
    condition: failed()
    steps:
      - script: echo this will run when A fails

  - job: C
    dependsOn:
      - A
      - B
    condition: succeeded('B')
    steps:
      - script: echo this will run when B runs and succeeds
